---
title: "get-data-somatic-snv"
author: "Jineta Banerjee"
date: "2022-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r lib_synapser, echo=FALSE, eval=TRUE, results='hide', message=FALSE, warning=FALSE, include=FALSE}

#library(synapser)
#library(synapserutils)

library(BiocManager)
library(gProfileR)
#library(GOsummaries)
library(tidyverse)
library(DT)
library(vcfR)  ##read vcf files
library(maftools)
#library(GenVisR)
library(magicfor)  ## store data from forloop as dataframe
library(magrittr)
#library(shiny)
library(glue)

library(reticulate)

```

```{python login_to_synapse, eval=TRUE, echo=FALSE, results='hide', message=FALSE, warning=FALSE, include=FALSE}

## The login credentials have been stored in .synapseConfig file in the home dir. If you dont have this setup, please make the file before trying to login.
import synapseclient
syn = synapseclient.Synapse()

syn.login()

```

## get SNV merged file

```{python mergedmaf, eval = FALSE}

#mergedmaf = syn.get("syn36553188", downloadLocation = "/Users/jineta/git/gitrepo/biobank-release-2/data")

#Download files using get-data-somatic-snv.ipynb script

```

## get clinical data

```{python clinical_data_from_tables, echo=FALSE, eval=TRUE, results='hide', message=FALSE, warning=FALSE}

import pandas as pd

#get clinical annotations
query = "SELECT distinct individualID, specimenID, tumorType, tissue, sex, age, bodyPart, isCellLine FROM syn30791643 WHERE ( assay = 'Whole Exome Sequencing' ) "

jhu_triplicates_clinicaldata = syn.tableQuery(query).asDataFrame()
jhu_triplicates_clinicaldata.columns

```

```{r maf file}

#convert specimenID column to Tumor_Sample_Barcode
py$jhu_triplicates_clinicaldata$Tumor_Sample_Barcode <- py$jhu_triplicates_clinicaldata$specimenID

jhu_triplicates_clinicaldata <- py$jhu_triplicates_clinicaldata

jhu_triplicates_clinicaldata$Tumor_Sample_Barcode <- stringr::str_replace_all(jhu_triplicates_clinicaldata$Tumor_Sample_Barcode," ","_")

# clean up names
jhu_triplicates_clinicaldata$Tumor_Sample_Barcode[jhu_triplicates_clinicaldata$specimenID == "2-015 Malignant Peripheral Nerve Sheath Tumor"] <- "2_015_Malignant_Peripheral_Nerve_Sheath_Tumor_TD"

jhu_triplicates_clinicaldata$Tumor_Sample_Barcode[jhu_triplicates_clinicaldata$specimenID == "2-016 Malignant Peripheral Nerve Sheath Tumor"] <- "2_016_TD"

jhu_triplicates_clinicaldata$Tumor_Sample_Barcode[jhu_triplicates_clinicaldata$specimenID == "2-009 Neurofibroma"] <- "2_009_Neurofibroma_TD"

```

```{r read_maf}

files <- (Sys.glob("/Users/jineta/git/gitrepo/biobank-release-2/data/somatic_snv_batch1_2_3/*.maf"))

listOfFiles <- lapply(files, function(x) maftools::read.maf(maf = x,
                                                            clinicalData = jhu_triplicates_clinicaldata)) 

somatic_snv <- maftools::merge_mafs(listOfFiles)


```

We are missing annotations for 
  2_015_TD
  



